{
  "Ford": [
    { "model": "Fiesta", "fuel": "petrol", "mpg": 50 },
    { "model": "Focus", "fuel": "diesel", "mpg": 60 },
    { "model": "Puma", "fuel": "petrol", "mpg": 47 },
    { "model": "Kuga", "fuel": "hybrid", "mpg": 42 },
    { "model": "Mondeo", "fuel": "diesel", "mpg": 55 },
    { "model": "EcoSport", "fuel": "petrol", "mpg": 45 },
    { "model": "Transit", "fuel": "diesel", "mpg": 30 },
    { "model": "Tourneo", "fuel": "diesel", "mpg": 32 },
    { "model": "Mustang", "fuel": "petrol", "mpg": 28 },
    { "model": "Edge", "fuel": "petrol", "mpg": 33 },
    { "model": "Galaxy", "fuel": "diesel", "mpg": 40 },
    { "model": "S‑Max", "fuel": "diesel", "mpg": 42 },
    { "model": "C‑Max", "fuel": "petrol", "mpg": 44 },
    { "model": "B‑Max", "fuel": "petrol", "mpg": 46 },
    { "model": "Ranger", "fuel": "diesel", "mpg": 35 },
    { "model": "Bronco", "fuel": "petrol", "mpg": 26 },
    { "model": "GT", "fuel": "petrol", "mpg": 25 },
    { "model": "Transit Connect", "fuel": "diesel", "mpg": 38 },
    { "model": "Tourneo Connect", "fuel": "diesel", "mpg": 36 },
    { "model": "Electrified Kuga", "fuel": "hybrid", "mpg": 47 }
  ],
  "Volkswagen": [
    { "model": "Golf", "fuel": "petrol", "mpg": 47 },
    { "model": "Polo", "fuel": "petrol", "mpg": 50 },
    { "model": "Tiguan", "fuel": "diesel", "mpg": 44 },
    { "model": "Passat", "fuel": "diesel", "mpg": 52 },
    { "model": "Up!", "fuel": "petrol", "mpg": 55 },
    { "model": "Arteon", "fuel": "petrol", "mpg": 38 },
    { "model": "Touran", "fuel": "diesel", "mpg": 48 },
    { "model": "Sharan", "fuel": "diesel", "mpg": 45 },
    { "model": "T‑Roc", "fuel": "petrol", "mpg": 42 },
    { "model": "T‑Cross", "fuel": "petrol", "mpg": 44 },
    { "model": "ID.3", "fuel": "electric", "kwh_per_mile": 0.30 },
    { "model": "ID.4", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "ID. Buzz", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Amarok", "fuel": "diesel", "mpg": 36 },
    { "model": "Caddy", "fuel": "diesel", "mpg": 42 },
    { "model": "e‑Golf", "fuel": "electric", "kwh_per_mile": 0.29 },
    { "model": "Golf Estate", "fuel": "diesel", "mpg": 50 },
    { "model": "Passat Estate", "fuel": "diesel", "mpg": 49 },
    { "model": "CC", "fuel": "petrol", "mpg": 39 },
    { "model": "Scirocco", "fuel": "petrol", "mpg": 35 }
  ],
  "BMW": [
    { "model": "3 Series", "fuel": "petrol", "mpg": 42 },
    { "model": "5 Series", "fuel": "diesel", "mpg": 50 },
    { "model": "1 Series", "fuel": "petrol", "mpg": 40 },
    { "model": "2 Series", "fuel": "petrol", "mpg": 38 },
    { "model": "X1", "fuel": "petrol", "mpg": 37 },
    { "model": "X3", "fuel": "diesel", "mpg": 45 },
    { "model": "X5", "fuel": "diesel", "mpg": 35 },
    { "model": "i3", "fuel": "electric", "kwh_per_mile": 0.28 },
    { "model": "i4", "fuel": "electric", "kwh_per_mile": 0.30 },
    { "model": "iX", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "M3", "fuel": "petrol", "mpg": 28 },
    { "model": "M4", "fuel": "petrol", "mpg": 27 },
    { "model": "Z4", "fuel": "petrol", "mpg": 30 },
    { "model": "X2", "fuel": "petrol", "mpg": 36 },
    { "model": "X4", "fuel": "diesel", "mpg": 40 },
    { "model": "X6", "fuel": "petrol", "mpg": 34 },
    { "model": "4 Series", "fuel": "petrol", "mpg": 39 },
    { "model": "6 Series", "fuel": "diesel", "mpg": 44 },
    { "model": "7 Series", "fuel": "petrol", "mpg": 32 },
    { "model": "M5", "fuel": "petrol", "mpg": 24 }
  ],
  "Audi": [
    { "model": "A1", "fuel": "petrol", "mpg": 48 },
    { "model": "A3", "fuel": "petrol", "mpg": 42 },
    { "model": "A4", "fuel": "diesel", "mpg": 50 },
    { "model": "A6", "fuel": "diesel", "mpg": 47 },
    { "model": "Q2", "fuel": "petrol", "mpg": 44 },
    { "model": "Q3", "fuel": "petrol", "mpg": 42 },
    { "model": "Q5", "fuel": "diesel", "mpg": 38 },
    { "model": "Q7", "fuel": "diesel", "mpg": 36 },
    { "model": "e‑tron", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "e‑tron GT", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "S3", "fuel": "petrol", "mpg": 37 },
    { "model": "S4", "fuel": "petrol", "mpg": 35 },
    { "model": "RS3", "fuel": "petrol", "mpg": 30 },
    { "model": "RS Q8", "fuel": "petrol", "mpg": 27 },
    { "model": "A5", "fuel": "petrol", "mpg": 40 },
    { "model": "A7", "fuel": "diesel", "mpg": 41 },
    { "model": "A8", "fuel": "diesel", "mpg": 43 },
    { "model": "Q8", "fuel": "diesel", "mpg": 35 },
    { "model": "S5", "fuel": "petrol", "mpg": 33 },
    { "model": "TT", "fuel": "petrol", "mpg": 37 }
  ],
  "Toyota": [
    { "model": "Yaris", "fuel": "hybrid", "mpg": 58 },
    { "model": "Corolla", "fuel": "hybrid", "mpg": 55 },
    { "model": "RAV4", "fuel": "hybrid", "mpg": 47 },
    { "model": "C‑HR", "fuel": "hybrid", "mpg": 50 },
    { "model": "Auris", "fuel": "petrol", "mpg": 48 },
    { "model": "Avensis", "fuel": "diesel", "mpg": 52 },
    { "model": "Prius", "fuel": "hybrid", "mpg": 56 },
    { "model": "Hilux", "fuel": "diesel", "mpg": 34 },
    { "model": "Urban Cruiser", "fuel": "petrol", "mpg": 45 },
    { "model": "Verso", "fuel": "diesel", "mpg": 49 },
    { "model": "Supra", "fuel": "petrol", "mpg": 30 },
    { "model": "Aygo", "fuel": "petrol", "mpg": 58 },
    { "model": "Proace", "fuel": "diesel", "mpg": 40 },
    { "model": "Proace Verso", "fuel": "diesel", "mpg": 38 },
    { "model": "Land Cruiser", "fuel": "diesel", "mpg": 31 },
    { "model": "Yaris Cross", "fuel": "hybrid", "mpg": 52 },
    { "model": "Camry", "fuel": "hybrid", "mpg": 48 },
    { "model": "GT86", "fuel": "petrol", "mpg": 33 },
    { "model": "RAV4 Plug‑in", "fuel": "hybrid", "mpg": 72 },
    { "model": "Corolla Touring", "fuel": "hybrid", "mpg": 54 }
  ],
  "Nissan": [
    { "model": "Qashqai", "fuel": "hybrid", "mpg": 44 },
    { "model": "Juke", "fuel": "petrol", "mpg": 46 },
    { "model": "Leaf", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "Micra", "fuel": "petrol", "mpg": 50 },
    { "model": "X‑Trail", "fuel": "diesel", "mpg": 42 },
    { "model": "Note", "fuel": "petrol", "mpg": 48 },
    { "model": "Primera", "fuel": "diesel", "mpg": 47 },
    { "model": "Almera", "fuel": "petrol", "mpg": 49 },
    { "model": "NV200", "fuel": "diesel", "mpg": 40 },
    { "model": "Evalia", "fuel": "diesel", "mpg": 39 },
    { "model": "GT‑R", "fuel": "petrol", "mpg": 23 },
    { "model": "350Z", "fuel": "petrol", "mpg": 26 },
    { "model": "370Z", "fuel": "petrol", "mpg": 24 },
    { "model": "Terrano", "fuel": "diesel", "mpg": 36 },
    { "model": "Patrol", "fuel": "petrol", "mpg": 22 },
    { "model": "Pulsar", "fuel": "petrol", "mpg": 45 },
    { "model": "Serena", "fuel": "petrol", "mpg": 41 },
    { "model": "Navara", "fuel": "diesel", "mpg": 34 },
    { "model": "Urvan", "fuel": "diesel", "mpg": 33 },
    { "model": "Rogue", "fuel": "petrol", "mpg": 27 }
  ],
  "Vauxhall": [
    { "model": "Corsa", "fuel": "petrol", "mpg": 47 },
    { "model": "Astra", "fuel": "diesel", "mpg": 48 },
    { "model": "Mokka", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Insignia", "fuel": "diesel", "mpg": 50 },
    { "model": "Grandland X", "fuel": "petrol", "mpg": 44 },
    { "model": "Crossland X", "fuel": "petrol", "mpg": 46 },
    { "model": "Combo", "fuel": "diesel", "mpg": 38 },
    { "model": "Vivaro", "fuel": "diesel", "mpg": 35 },
    { "model": "Zafira", "fuel": "petrol", "mpg": 42 },
    { "model": "Monaro", "fuel": "petrol", "mpg": 29 },
    { "model": "Vectra", "fuel": "diesel", "mpg": 43 },
    { "model": "Meriva", "fuel": "petrol", "mpg": 45 },
    { "model": "Tigra", "fuel": "petrol", "mpg": 47 },
    { "model": "Calibra", "fuel": "petrol", "mpg": 38 },
    { "model": "Manta", "fuel": "petrol", "mpg": 32 },
    { "model": "Senator", "fuel": "diesel", "mpg": 37 },
    { "model": "Omega", "fuel": "diesel", "mpg": 39 },
    { "model": "Frontera", "fuel": "petrol", "mpg": 35 },
    { "model": "Ampera", "fuel": "electric", "kwh_per_mile": 0.28 },
    { "model": "GT", "fuel": "petrol", "mpg": 30 }
  ],
  "Mercedes-Benz": [
    { "model": "A Class", "fuel": "petrol", "mpg": 45 },
    { "model": "B Class", "fuel": "petrol", "mpg": 42 },
    { "model": "C Class", "fuel": "diesel", "mpg": 40 },
    { "model": "E Class", "fuel": "diesel", "mpg": 44 },
    { "model": "S Class", "fuel": "petrol", "mpg": 35 },
    { "model": "GLA", "fuel": "petrol", "mpg": 38 },
    { "model": "GLC", "fuel": "diesel", "mpg": 36 },
    { "model": "GLE", "fuel": "diesel", "mpg": 34 },
    { "model": "GLS", "fuel": "diesel", "mpg": 32 },
    { "model": "EQC", "fuel": "electric", "kwh_per_mile": 0.35 },
    { "model": "EQB", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "EQA", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "CLS", "fuel": "petrol", "mpg": 33 },
    { "model": "G Class", "fuel": "petrol", "mpg": 25 },
    { "model": "V Class", "fuel": "diesel", "mpg": 28 },
    { "model": "Vito", "fuel": "diesel", "mpg": 30 },
    { "model": "Sprinter", "fuel": "diesel", "mpg": 27 },
    { "model": "SL", "fuel": "petrol", "mpg": 29 },
    { "model": "SLC", "fuel": "petrol", "mpg": 31 },
    { "model": "AMG GT", "fuel": "petrol", "mpg": 22 }
  ],
  "Hyundai": [
    { "model": "i10", "fuel": "petrol", "mpg": 55 },
    { "model": "i20", "fuel": "petrol", "mpg": 52 },
    { "model": "i30", "fuel": "petrol", "mpg": 47 },
    { "model": "i30 Fastback", "fuel": "petrol", "mpg": 46 },
    { "model": "i40", "fuel": "diesel", "mpg": 44 },
    { "model": "Tucson", "fuel": "hybrid", "mpg": 45 },
    { "model": "Kona", "fuel": "petrol", "mpg": 48 },
    { "model": "Kona Electric", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "Santa Fe", "fuel": "diesel", "mpg": 40 },
    { "model": "Bayon", "fuel": "petrol", "mpg": 50 },
    { "model": "Nexo", "fuel": "hydrogen", "mpg": 60 },
    { "model": "i20 N", "fuel": "petrol", "mpg": 38 },
    { "model": "i30 N", "fuel": "petrol", "mpg": 35 },
    { "model": "Staria", "fuel": "diesel", "mpg": 33 },
    { "model": "H‑1", "fuel": "diesel", "mpg": 28 },
    { "model": "Coupe", "fuel": "petrol", "mpg": 34 },
    { "model": "Accent", "fuel": "petrol", "mpg": 48 },
    { "model": "Excel", "fuel": "diesel", "mpg": 46 },
    { "model": "Veloster", "fuel": "petrol", "mpg": 36 },
    { "model": "Elantra", "fuel": "hybrid", "mpg": 50 }
  ],
  "Kia": [
    { "model": "Picanto", "fuel": "petrol", "mpg": 55 },
    { "model": "Rio", "fuel": "petrol", "mpg": 50 },
    { "model": "Ceed", "fuel": "petrol", "mpg": 47 },
    { "model": "Ceed SW", "fuel": "diesel", "mpg": 48 },
    { "model": "XCeed", "fuel": "hybrid", "mpg": 45 },
    { "model": "Sportage", "fuel": "hybrid", "mpg": 43 },
    { "model": "Sorento", "fuel": "diesel", "mpg": 39 },
    { "model": "Stonic", "fuel": "petrol", "mpg": 46 },
    { "model": "EV6", "fuel": "electric", "kwh_per_mile": 0.29 },
    { "model": "Niro", "fuel": "hybrid", "mpg": 50 },
    { "model": "Soul", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "Carens", "fuel": "diesel", "mpg": 42 },
    { "model": "Cerato", "fuel": "petrol", "mpg": 47 },
    { "model": "Optima", "fuel": "hybrid", "mpg": 49 },
    { "model": "Mohave", "fuel": "diesel", "mpg": 35 },
    { "model": "ProCeed", "fuel": "petrol", "mpg": 44 },
    { "model": "Venga", "fuel": "diesel", "mpg": 45 },
    { "model": "K900", "fuel": "petrol", "mpg": 32 },
    { "model": "Picanto X-Line", "fuel": "petrol", "mpg": 53 },
    { "model": "Ceed GT", "fuel": "petrol", "mpg": 38 }
  ],
  "Skoda": [
    { "model": "Fabia", "fuel": "petrol", "mpg": 52 },
    { "model": "Octavia", "fuel": "petrol", "mpg": 47 },
    { "model": "Octavia Estate", "fuel": "diesel", "mpg": 48 },
    { "model": "Scala", "fuel": "petrol", "mpg": 50 },
    { "model": "Kamiq", "fuel": "petrol", "mpg": 46 },
    { "model": "Karoq", "fuel": "diesel", "mpg": 44 },
    { "model": "Kodiaq", "fuel": "diesel", "mpg": 40 },
    { "model": "Enyaq iV", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "Rapid", "fuel": "petrol", "mpg": 47 },
    { "model": "Yeti", "fuel": "diesel", "mpg": 43 },
    { "model": "Superb", "fuel": "diesel", "mpg": 50 },
    { "model": "Superb Estate", "fuel": "diesel", "mpg": 48 },
    { "model": "Roomster", "fuel": "petrol", "mpg": 45 },
    { "model": "Citigo", "fuel": "petrol", "mpg": 55 },
    { "model": "Felicia", "fuel": "petrol", "mpg": 50 },
    { "model": "Octavia RS", "fuel": "petrol", "mpg": 40 },
    { "model": "Fabia Combi", "fuel": "diesel", "mpg": 46 },
    { "model": "Superb iV", "fuel": "hybrid", "mpg": 52 },
    { "model": "Enyaq Coupe iV", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Octavia iV", "fuel": "hybrid", "mpg": 50 }
  ]
  "Mercedes-Benz": [
    { "model": "A Class", "fuel": "petrol", "mpg": 45 },
    { "model": "B Class", "fuel": "petrol", "mpg": 42 },
    { "model": "C Class", "fuel": "diesel", "mpg": 40 },
    { "model": "E Class", "fuel": "diesel", "mpg": 44 },
    { "model": "S Class", "fuel": "petrol", "mpg": 35 },
    { "model": "GLA", "fuel": "petrol", "mpg": 38 },
    { "model": "GLC", "fuel": "diesel", "mpg": 36 },
    { "model": "GLE", "fuel": "diesel", "mpg": 34 },
    { "model": "GLS", "fuel": "diesel", "mpg": 32 },
    { "model": "EQC", "fuel": "electric", "kwh_per_mile": 0.35 },
    { "model": "EQB", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "EQA", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "CLS", "fuel": "petrol", "mpg": 33 },
    { "model": "G Class", "fuel": "petrol", "mpg": 25 },
    { "model": "V Class", "fuel": "diesel", "mpg": 28 },
    { "model": "Vito", "fuel": "diesel", "mpg": 30 },
    { "model": "Sprinter", "fuel": "diesel", "mpg": 27 },
    { "model": "SL", "fuel": "petrol", "mpg": 29 },
    { "model": "SLC", "fuel": "petrol", "mpg": 31 },
    { "model": "AMG GT", "fuel": "petrol", "mpg": 22 }
  ],
  "Hyundai": [
    { "model": "i10", "fuel": "petrol", "mpg": 55 },
    { "model": "i20", "fuel": "petrol", "mpg": 52 },
    { "model": "i30", "fuel": "petrol", "mpg": 47 },
    { "model": "i30 Fastback", "fuel": "petrol", "mpg": 46 },
    { "model": "i40", "fuel": "diesel", "mpg": 44 },
    { "model": "Tucson", "fuel": "hybrid", "mpg": 45 },
    { "model": "Kona", "fuel": "petrol", "mpg": 48 },
    { "model": "Kona Electric", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "Santa Fe", "fuel": "diesel", "mpg": 40 },
    { "model": "Bayon", "fuel": "petrol", "mpg": 50 },
    { "model": "Nexo", "fuel": "hydrogen", "mpg": 60 },
    { "model": "i20 N", "fuel": "petrol", "mpg": 38 },
    { "model": "i30 N", "fuel": "petrol", "mpg": 35 },
    { "model": "Staria", "fuel": "diesel", "mpg": 33 },
    { "model": "H‑1", "fuel": "diesel", "mpg": 28 },
    { "model": "Coupe", "fuel": "petrol", "mpg": 34 },
    { "model": "Accent", "fuel": "petrol", "mpg": 48 },
    { "model": "Excel", "fuel": "diesel", "mpg": 46 },
    { "model": "Veloster", "fuel": "petrol", "mpg": 36 },
    { "model": "Elantra", "fuel": "hybrid", "mpg": 50 }
  ],
  "Kia": [
    { "model": "Picanto", "fuel": "petrol", "mpg": 55 },
    { "model": "Rio", "fuel": "petrol", "mpg": 50 },
    { "model": "Ceed", "fuel": "petrol", "mpg": 47 },
    { "model": "Ceed SW", "fuel": "diesel", "mpg": 48 },
    { "model": "XCeed", "fuel": "hybrid", "mpg": 45 },
    { "model": "Sportage", "fuel": "hybrid", "mpg": 43 },
    { "model": "Sorento", "fuel": "diesel", "mpg": 39 },
    { "model": "Stonic", "fuel": "petrol", "mpg": 46 },
    { "model": "EV6", "fuel": "electric", "kwh_per_mile": 0.29 },
    { "model": "Niro", "fuel": "hybrid", "mpg": 50 },
    { "model": "Soul", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "Carens", "fuel": "diesel", "mpg": 42 },
    { "model": "Cerato", "fuel": "petrol", "mpg": 47 },
    { "model": "Optima", "fuel": "hybrid", "mpg": 49 },
    { "model": "Mohave", "fuel": "diesel", "mpg": 35 },
    { "model": "ProCeed", "fuel": "petrol", "mpg": 44 },
    { "model": "Venga", "fuel": "diesel", "mpg": 45 },
    { "model": "K900", "fuel": "petrol", "mpg": 32 },
    { "model": "Picanto X-Line", "fuel": "petrol", "mpg": 53 },
    { "model": "Ceed GT", "fuel": "petrol", "mpg": 38 }
  ],
  "Skoda": [
    { "model": "Fabia", "fuel": "petrol", "mpg": 52 },
    { "model": "Octavia", "fuel": "petrol", "mpg": 47 },
    { "model": "Octavia Estate", "fuel": "diesel", "mpg": 48 },
    { "model": "Scala", "fuel": "petrol", "mpg": 50 },
    { "model": "Kamiq", "fuel": "petrol", "mpg": 46 },
    { "model": "Karoq", "fuel": "diesel", "mpg": 44 },
    { "model": "Kodiaq", "fuel": "diesel", "mpg": 40 },
    { "model": "Enyaq iV", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "Rapid", "fuel": "petrol", "mpg": 47 },
    { "model": "Yeti", "fuel": "diesel", "mpg": 43 },
    { "model": "Superb", "fuel": "diesel", "mpg": 50 },
    { "model": "Superb Estate", "fuel": "diesel", "mpg": 48 },
    { "model": "Roomster", "fuel": "petrol", "mpg": 45 },
    { "model": "Citigo", "fuel": "petrol", "mpg": 55 },
    { "model": "Felicia", "fuel": "petrol", "mpg": 50 },
    { "model": "Octavia RS", "fuel": "petrol", "mpg": 40 },
    { "model": "Fabia Combi", "fuel": "diesel", "mpg": 46 },
    { "model": "Superb iV", "fuel": "hybrid", "mpg": 52 },
    { "model": "Enyaq Coupe iV", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Octavia iV", "fuel": "hybrid", "mpg": 50 }
  ]
}
{
  "Alfa Romeo": [
    { "model": "Giulia", "fuel": "petrol", "mpg": 38 },
    { "model": "Stelvio", "fuel": "petrol", "mpg": 36 },
    { "model": "MiTo", "fuel": "petrol", "mpg": 45 },
    { "model": "147", "fuel": "petrol", "mpg": 40 },
    { "model": "156", "fuel": "diesel", "mpg": 42 },
    { "model": "159", "fuel": "diesel", "mpg": 40 },
    { "model": "GT", "fuel": "petrol", "mpg": 34 },
    { "model": "Spider", "fuel": "petrol", "mpg": 32 },
    { "model": "Brera", "fuel": "petrol", "mpg": 30 },
    { "model": "GTV", "fuel": "petrol", "mpg": 28 },
    { "model": "Sprint", "fuel": "petrol", "mpg": 46 },
    { "model": "Giulietta", "fuel": "petrol", "mpg": 43 },
    { "model": "90", "fuel": "petrol", "mpg": 33 },
    { "model": "33", "fuel": "petrol", "mpg": 35 },
    { "model": "164", "fuel": "diesel", "mpg": 35 },
    { "model": "Super", "fuel": "petrol", "mpg": 37 },
    { "model": "2600", "fuel": "petrol", "mpg": 23 },
    { "model": "Giulia GT", "fuel": "petrol", "mpg": 31 },
    { "model": "Alfasud", "fuel": "petrol", "mpg": 47 },
    { "model": "RZ", "fuel": "petrol", "mpg": 22 }
  ],
  "Aston Martin": [
    { "model": "DB11", "fuel": "petrol", "mpg": 22 },
    { "model": "Vantage", "fuel": "petrol", "mpg": 21 },
    { "model": "DBS", "fuel": "petrol", "mpg": 20 },
    { "model": "Rapide", "fuel": "petrol", "mpg": 18 },
    { "model": "DB9", "fuel": "petrol", "mpg": 19 },
    { "model": "Vanquish", "fuel": "petrol", "mpg": 17 },
    { "model": "Cygnet", "fuel": "petrol", "mpg": 40 },
    { "model": "V12 Vantage", "fuel": "petrol", "mpg": 15 },
    { "model": "Lagonda", "fuel": "petrol", "mpg": 16 },
    { "model": "DBX", "fuel": "petrol", "mpg": 24 },
    { "model": "V8 Vantage", "fuel": "petrol", "mpg": 23 },
    { "model": "DB6", "fuel": "petrol", "mpg": 14 },
    { "model": "DB4", "fuel": "petrol", "mpg": 13 },
    { "model": "One‑77", "fuel": "petrol", "mpg": 12 },
    { "model": "V8", "fuel": "petrol", "mpg": 20 },
    { "model": "GT Zagato", "fuel": "petrol", "mpg": 18 },
    { "model": "Project 212", "fuel": "petrol", "mpg": 19 },
    { "model": "Victor", "fuel": "petrol", "mpg": 17 },
    { "model": "AMR Pro", "fuel": "petrol", "mpg": 11 },
    { "model": "Valhalla", "fuel": "hybrid", "mpg": 40 }
  ],
  "Bentley": [
    { "model": "Continental GT", "fuel": "petrol", "mpg": 18 },
    { "model": "Flying Spur", "fuel": "petrol", "mpg": 17 },
    { "model": "Bentayga", "fuel": "diesel", "mpg": 25 },
    { "model": "Mulsanne", "fuel": "petrol", "mpg": 15 },
    { "model": "Arnage", "fuel": "petrol", "mpg": 13 },
    { "model": "Azure", "fuel": "petrol", "mpg": 12 },
    { "model": "Brooklands", "fuel": "petrol", "mpg": 14 },
    { "model": "GT Speed", "fuel": "petrol", "mpg": 16 },
    { "model": "Turbo R", "fuel": "petrol", "mpg": 14 },
    { "model": "Bentayga Hybrid", "fuel": "hybrid", "mpg": 35 },
    { "model": "Continental Supersports", "fuel": "petrol", "mpg": 13 },
    { "model": "Flying Spur Hybrid", "fuel": "hybrid", "mpg": 36 },
    { "model": "Bentayga Speed", "fuel": "petrol", "mpg": 20 },
    { "model": "R Type", "fuel": "diesel", "mpg": 23 },
    { "model": "S1", "fuel": "petrol", "mpg": 13 },
    { "model": "Mark VI", "fuel": "petrol", "mpg": 12 },
    { "model": "8 Litre", "fuel": "petrol", "mpg": 10 },
    { "model": "Blower", "fuel": "petrol", "mpg": 8 },
    { "model": "Speed Six", "fuel": "petrol", "mpg": 9 },
    { "model": "Four Door", "fuel": "petrol", "mpg": 16 }
  ],
  "Bugatti": [
    { "model": "Veyron", "fuel": "petrol", "mpg": 9 },
    { "model": "Chiron", "fuel": "petrol", "mpg": 10 },
    { "model": "Divo", "fuel": "petrol", "mpg": 9 },
    { "model": "Centodieci", "fuel": "petrol", "mpg": 8 },
    { "model": "La Voiture Noire", "fuel": "petrol", "mpg": 8 },
    { "model": "Pur Sport", "fuel": "petrol", "mpg": 9 },
    { "model": "EB110", "fuel": "petrol", "mpg": 9 },
    { "model": "Type 57", "fuel": "petrol", "mpg": 15 },
    { "model": "Atlantic", "fuel": "petrol", "mpg": 14 },
    { "model": "Galibier", "fuel": "petrol", "mpg": 11 },
    { "model": "Super Sport", "fuel": "petrol", "mpg": 8 },
    { "model": "Grand Sport", "fuel": "petrol", "mpg": 9 },
    { "model": "Baby II", "fuel": "petrol", "mpg": 18 },
    { "model": "Type 13", "fuel": "petrol", "mpg": 22 },
    { "model": "Type 35", "fuel": "petrol", "mpg": 20 },
    { "model": "Type 41 Royale", "fuel": "petrol", "mpg": 5 },
    { "model": "Bolide", "fuel": "petrol", "mpg": 7 },
    { "model": "Type 32", "fuel": "petrol", "mpg": 16 },
    { "model": "Type 43", "fuel": "petrol", "mpg": 19 },
    { "model": "GT", "fuel": "petrol", "mpg": 12 }
  ],
  "Cadillac": [
    { "model": "CTS", "fuel": "petrol", "mpg": 25 },
    { "model": "ATS", "fuel": "petrol", "mpg": 27 },
    { "model": "XTS", "fuel": "petrol", "mpg": 23 },
    { "model": "Escalade", "fuel": "petrol", "mpg": 18 },
    { "model": "CT4", "fuel": "petrol", "mpg": 28 },
    { "model": "CT5", "fuel": "petrol", "mpg": 27 },
    { "model": "XT4", "fuel": "petrol", "mpg": 26 },
    { "model": "XT5", "fuel": "petrol", "mpg": 24 },
    { "model": "XT6", "fuel": "petrol", "mpg": 22 },
    { "model": "ELR", "fuel": "hybrid", "mpg": 40 },
    { "model": "Catera", "fuel": "petrol", "mpg": 20 },
    { "model": "Seville", "fuel": "petrol", "mpg": 21 },
    { "model": "DeVille", "fuel": "petrol", "mpg": 19 },
    { "model": "Fleetwood", "fuel": "petrol", "mpg": 17 },
    { "model": "DTS", "fuel": "petrol", "mpg": 18 },
    { "model": "Brougham", "fuel": "petrol", "mpg": 16 },
    { "model": "Allanté", "fuel": "petrol", "mpg": 15 },
    { "model": "StS", "fuel": "petrol", "mpg": 20 },
    { "model": "Cimarron", "fuel": "petrol", "mpg": 25 },
    { "model": "XLR", "fuel": "petrol", "mpg": 23 }
  ]
}
{
  "Jaguar": [
    { "model": "XE", "fuel": "petrol", "mpg": 32 },
    { "model": "XF", "fuel": "diesel", "mpg": 45 },
    { "model": "XJ", "fuel": "petrol", "mpg": 28 },
    { "model": "F-Type", "fuel": "petrol", "mpg": 25 },
    { "model": "E-Pace", "fuel": "diesel", "mpg": 42 },
    { "model": "F-Pace", "fuel": "diesel", "mpg": 40 },
    { "model": "I-Pace", "fuel": "electric", "kwh_per_mile": 0.35 },
    { "model": "S-Type", "fuel": "diesel", "mpg": 38 },
    { "model": "X-Type", "fuel": "diesel", "mpg": 36 },
    { "model": "Mark 2", "fuel": "petrol", "mpg": 22 },
    { "model": "Mark 1", "fuel": "petrol", "mpg": 24 },
    { "model": "E-Type", "fuel": "petrol", "mpg": 19 },
    { "model": "Mk IX", "fuel": "petrol", "mpg": 18 },
    { "model": "Mk X", "fuel": "petrol", "mpg": 17 },
    { "model": "Mk II", "fuel": "petrol", "mpg": 20 },
    { "model": "SS", "fuel": "petrol", "mpg": 21 },
    { "model": "C-Type", "fuel": "petrol", "mpg": 16 },
    { "model": "D-Type", "fuel": "petrol", "mpg": 15 },
    { "model": "F-Pace SVR", "fuel": "petrol", "mpg": 27 },
    { "model": "XE SV Project 8", "fuel": "petrol", "mpg": 23 }
  ],
  "Land Rover": [
    { "model": "Range Rover", "fuel": "diesel", "mpg": 27 },
    { "model": "Range Rover Sport", "fuel": "diesel", "mpg": 25 },
    { "model": "Range Rover Velar", "fuel": "diesel", "mpg": 28 },
    { "model": "Discovery", "fuel": "diesel", "mpg": 30 },
    { "model": "Discovery Sport", "fuel": "diesel", "mpg": 32 },
    { "model": "Defender", "fuel": "diesel", "mpg": 33 },
    { "model": "Freelander", "fuel": "diesel", "mpg": 31 },
    { "model": "Series I", "fuel": "diesel", "mpg": 20 },
    { "model": "Series II", "fuel": "diesel", "mpg": 21 },
    { "model": "Series III", "fuel": "diesel", "mpg": 22 },
    { "model": "Range Rover Evoque", "fuel": "diesel", "mpg": 34 },
    { "model": "Discovery SVX", "fuel": "diesel", "mpg": 28 },
    { "model": "Defender 90", "fuel": "diesel", "mpg": 30 },
    { "model": "Defender 110", "fuel": "diesel", "mpg": 29 },
    { "model": "Range Rover Autobiography", "fuel": "diesel", "mpg": 26 },
    { "model": "Discovery HSE", "fuel": "diesel", "mpg": 27 },
    { "model": "Range Rover Sport SVR", "fuel": "petrol", "mpg": 23 },
    { "model": "Defender V8", "fuel": "petrol", "mpg": 20 },
    { "model": "Freelander 2", "fuel": "diesel", "mpg": 29 },
    { "model": "Discovery Td5", "fuel": "diesel", "mpg": 25 }
  ],
  "Mazda": [
    { "model": "2", "fuel": "petrol", "mpg": 55 },
    { "model": "3", "fuel": "petrol", "mpg": 50 },
    { "model": "6", "fuel": "diesel", "mpg": 45 },
    { "model": "CX-3", "fuel": "diesel", "mpg": 42 },
    { "model": "CX-30", "fuel": "petrol", "mpg": 46 },
    { "model": "CX-5", "fuel": "diesel", "mpg": 40 },
    { "model": "MX-5", "fuel": "petrol", "mpg": 35 },
    { "model": "CX-50", "fuel": "petrol", "mpg": 38 },
    { "model": "CX-60", "fuel": "hybrid", "mpg": 48 },
    { "model": "CX-70", "fuel": "hybrid", "mpg": 45 },
    { "model": "RX-8", "fuel": "petrol", "mpg": 21 },
    { "model": "RX-7", "fuel": "petrol", "mpg": 20 },
    { "model": "5", "fuel": "diesel", "mpg": 44 },
    { "model": "Premacy", "fuel": "diesel", "mpg": 41 },
    { "model": "MPV", "fuel": "petrol", "mpg": 30 },
    { "model": "Demio", "fuel": "petrol", "mpg": 52 },
    { "model": "Familia", "fuel": "petrol", "mpg": 47 },
    { "model": "Biante", "fuel": "diesel", "mpg": 40 },
    { "model": "CX-7", "fuel": "petrol", "mpg": 28 },
    { "model": "6 MPS", "fuel": "petrol", "mpg": 25 }
  ],
  "Peugeot": [
    { "model": "108", "fuel": "petrol", "mpg": 55 },
    { "model": "208", "fuel": "petrol", "mpg": 50 },
    { "model": "308", "fuel": "diesel", "mpg": 48 },
    { "model": "508", "fuel": "diesel", "mpg": 47 },
    { "model": "2008", "fuel": "petrol", "mpg": 46 },
    { "model": "3008", "fuel": "diesel", "mpg": 45 },
    { "model": "5008", "fuel": "diesel", "mpg": 44 },
    { "model": "Rifter", "fuel": "diesel", "mpg": 42 },
    { "model": "Traveller", "fuel": "diesel", "mpg": 38 },
    { "model": "Partner", "fuel": "diesel", "mpg": 36 },
    { "model": "RCZ", "fuel": "petrol", "mpg": 37 },
    { "model": "3008 Hybrid", "fuel": "hybrid", "mpg": 50 },
    { "model": "508 Hybrid", "fuel": "hybrid", "mpg": 49 },
    { "model": "e-208", "fuel": "electric", "kwh_per_mile": 0.30 },
    { "model": "e-2008", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "EXPERT", "fuel": "diesel", "mpg": 35 },
    { "model": "Bipper", "fuel": "diesel", "mpg": 34 },
    { "model": "e-EXPERT", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "e-Traveller", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "J5", "fuel": "diesel", "mpg": 33 }
  ]
}
{
  "Renault": [
    { "model": "Clio", "fuel": "petrol", "mpg": 52 },
    { "model": "Megane", "fuel": "diesel", "mpg": 48 },
    { "model": "Captur", "fuel": "petrol", "mpg": 47 },
    { "model": "Kadjar", "fuel": "diesel", "mpg": 45 },
    { "model": "Talisman", "fuel": "diesel", "mpg": 44 },
    { "model": "Zoe", "fuel": "electric", "kwh_per_mile": 0.28 },
    { "model": "Kangoo", "fuel": "diesel", "mpg": 42 },
    { "model": "Trafic", "fuel": "diesel", "mpg": 36 },
    { "model": "Master", "fuel": "diesel", "mpg": 35 },
    { "model": "Espace", "fuel": "diesel", "mpg": 40 },
    { "model": "Scenic", "fuel": "diesel", "mpg": 44 },
    { "model": "Wind", "fuel": "petrol", "mpg": 42 },
    { "model": "Laguna", "fuel": "diesel", "mpg": 38 },
    { "model": "5 GT", "fuel": "petrol", "mpg": 35 },
    { "model": "Alpine A110", "fuel": "petrol", "mpg": 34 },
    { "model": "Clio RS", "fuel": "petrol", "mpg": 36 },
    { "model": "Megane RS", "fuel": "petrol", "mpg": 32 },
    { "model": "Koleos", "fuel": "diesel", "mpg": 39 },
    { "model": "Arkana", "fuel": "hybrid", "mpg": 45 },
    { "model": "Twingo", "fuel": "petrol", "mpg": 50 }
  ],
  "Fiat": [
    { "model": "500", "fuel": "petrol", "mpg": 55 },
    { "model": "Panda", "fuel": "petrol", "mpg": 50 },
    { "model": "Punto", "fuel": "petrol", "mpg": 47 },
    { "model": "Tipo", "fuel": "diesel", "mpg": 45 },
    { "model": "500X", "fuel": "petrol", "mpg": 46 },
    { "model": "500L", "fuel": "petrol", "mpg": 44 },
    { "model": "Doblo", "fuel": "diesel", "mpg": 42 },
    { "model": "Panda 4x4", "fuel": "petrol", "mpg": 48 },
    { "model": "Fullback", "fuel": "diesel", "mpg": 35 },
    { "model": "Strada", "fuel": "diesel", "mpg": 34 },
    { "model": "Cinquecento", "fuel": "petrol", "mpg": 53 },
    { "model": "Bravo", "fuel": "diesel", "mpg": 40 },
    { "model": "Barchetta", "fuel": "petrol", "mpg": 38 },
    { "model": "Multipla", "fuel": "diesel", "mpg": 41 },
    { "model": "Marea", "fuel": "petrol", "mpg": 36 },
    { "model": "Sedici", "fuel": "diesel", "mpg": 39 },
    { "model": "Ulysse", "fuel": "diesel", "mpg": 37 },
    { "model": "Fiorino", "fuel": "diesel", "mpg": 43 },
    { "model": "500e", "fuel": "electric", "kwh_per_mile": 0.29 },
    { "model": "124 Spider", "fuel": "petrol", "mpg": 33 }
  ],
  "Mini": [
    { "model": "Hatch", "fuel": "petrol", "mpg": 47 },
    { "model": "Clubman", "fuel": "diesel", "mpg": 50 },
    { "model": "Countryman", "fuel": "hybrid", "mpg": 45 },
    { "model": "Convertible", "fuel": "petrol", "mpg": 44 },
    { "model": "Paceman", "fuel": "petrol", "mpg": 40 },
    { "model": "Cooper", "fuel": "petrol", "mpg": 46 },
    { "model": "Cooper S", "fuel": "petrol", "mpg": 38 },
    { "model": "John Cooper Works", "fuel": "petrol", "mpg": 34 },
    { "model": "Electric", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "One", "fuel": "petrol", "mpg": 48 },
    { "model": "Clubvan", "fuel": "diesel", "mpg": 50 },
    { "model": "Rover Mini", "fuel": "petrol", "mpg": 35 },
    { "model": "Classic Mini", "fuel": "petrol", "mpg": 36 },
    { "model": "Mini 1275GT", "fuel": "petrol", "mpg": 32 },
    { "model": "Mini Cooper SE", "fuel": "electric", "kwh_per_mile": 0.30 },
    { "model": "Mini Countryman SE", "fuel": "hybrid", "mpg": 42 },
    { "model": "Mini Clubman JCW", "fuel": "petrol", "mpg": 33 },
    { "model": "Mini Paceman JCW", "fuel": "petrol", "mpg": 31 },
    { "model": "Mini Cooper D", "fuel": "diesel", "mpg": 52 },
    { "model": "Mini Cooper SD", "fuel": "diesel", "mpg": 50 }
  ],
  "Honda": [
    { "model": "Civic", "fuel": "petrol", "mpg": 45 },
    { "model": "Accord", "fuel": "petrol", "mpg": 42 },
    { "model": "CR-V", "fuel": "hybrid", "mpg": 44 },
    { "model": "HR-V", "fuel": "petrol", "mpg": 46 },
    { "model": "Jazz", "fuel": "hybrid", "mpg": 50 },
    { "model": "Insight", "fuel": "hybrid", "mpg": 52 },
    { "model": "NSX", "fuel": "petrol", "mpg": 22 },
    { "model": "Integra", "fuel": "petrol", "mpg": 40 },
    { "model": "Prelude", "fuel": "petrol", "mpg": 38 },
    { "model": "S2000", "fuel": "petrol", "mpg": 25 },
    { "model": "Civic Type R", "fuel": "petrol", "mpg": 33 },
    { "model": "CR-Z", "fuel": "hybrid", "mpg": 48 },
    { "model": "Pilot", "fuel": "petrol", "mpg": 24 },
    { "model": "Ridgeline", "fuel": "petrol", "mpg": 20 },
    { "model": "Element", "fuel": "petrol", "mpg": 28 },
    { "model": "FR-V", "fuel": "diesel", "mpg": 41 },
    { "model": "Legend", "fuel": "petrol", "mpg": 29 },
    { "model": "Odyssey", "fuel": "petrol", "mpg": 27 },
    { "model": "S660", "fuel": "petrol", "mpg": 35 },
    { "model": "City", "fuel": "petrol", "mpg": 48 }
  ]
}
{
  "Suzuki": [
    { "model": "Swift", "fuel": "petrol", "mpg": 52 },
    { "model": "Vitara", "fuel": "petrol", "mpg": 44 },
    { "model": "Jimny", "fuel": "petrol", "mpg": 35 },
    { "model": "Baleno", "fuel": "petrol", "mpg": 55 },
    { "model": "S-Cross", "fuel": "diesel", "mpg": 46 },
    { "model": "Celerio", "fuel": "petrol", "mpg": 60 },
    { "model": "Alto", "fuel": "petrol", "mpg": 62 },
    { "model": "Ignis", "fuel": "hybrid", "mpg": 50 },
    { "model": "Splash", "fuel": "petrol", "mpg": 48 },
    { "model": "Liana", "fuel": "petrol", "mpg": 40 },
    { "model": "Grand Vitara", "fuel": "petrol", "mpg": 36 },
    { "model": "SX4", "fuel": "diesel", "mpg": 42 },
    { "model": "XL7", "fuel": "petrol", "mpg": 25 },
    { "model": "Every", "fuel": "petrol", "mpg": 30 },
    { "model": "Equator", "fuel": "diesel", "mpg": 28 },
    { "model": "Grand Vitara XL-7", "fuel": "diesel", "mpg": 32 },
    { "model": "Vitara Brezza", "fuel": "diesel", "mpg": 44 },
    { "model": "Kizashi", "fuel": "petrol", "mpg": 35 },
    { "model": "X-90", "fuel": "petrol", "mpg": 22 },
    { "model": "Swift Sport", "fuel": "petrol", "mpg": 40 }
  ],
  "Mitsubishi": [
    { "model": "Outlander", "fuel": "hybrid", "mpg": 44 },
    { "model": "ASX", "fuel": "petrol", "mpg": 42 },
    { "model": "Eclipse Cross", "fuel": "petrol", "mpg": 41 },
    { "model": "L200", "fuel": "diesel", "mpg": 33 },
    { "model": "Pajero", "fuel": "diesel", "mpg": 28 },
    { "model": "Mirage", "fuel": "petrol", "mpg": 48 },
    { "model": "Space Star", "fuel": "petrol", "mpg": 46 },
    { "model": "i-MiEV", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "Galant", "fuel": "petrol", "mpg": 30 },
    { "model": "Colt", "fuel": "petrol", "mpg": 38 },
    { "model": "Lancer", "fuel": "petrol", "mpg": 35 },
    { "model": "Outlander PHEV", "fuel": "hybrid", "mpg": 48 },
    { "model": "Shogun", "fuel": "diesel", "mpg": 25 },
    { "model": "Montero", "fuel": "diesel", "mpg": 26 },
    { "model": "3000GT", "fuel": "petrol", "mpg": 22 },
    { "model": "Pajero Sport", "fuel": "diesel", "mpg": 30 },
    { "model": "Eclipse", "fuel": "petrol", "mpg": 28 },
    { "model": "Outlander Sport", "fuel": "petrol", "mpg": 33 },
    { "model": "i-MiEV Plus", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Lancer Evolution", "fuel": "petrol", "mpg": 24 }
  ],
  "Lexus": [
    { "model": "RX", "fuel": "hybrid", "mpg": 44 },
    { "model": "NX", "fuel": "hybrid", "mpg": 42 },
    { "model": "UX", "fuel": "hybrid", "mpg": 46 },
    { "model": "ES", "fuel": "hybrid", "mpg": 50 },
    { "model": "LS", "fuel": "hybrid", "mpg": 35 },
    { "model": "IS", "fuel": "petrol", "mpg": 38 },
    { "model": "RC", "fuel": "petrol", "mpg": 34 },
    { "model": "LC", "fuel": "hybrid", "mpg": 40 },
    { "model": "GS", "fuel": "petrol", "mpg": 36 },
    { "model": "GX", "fuel": "petrol", "mpg": 25 },
    { "model": "CT", "fuel": "hybrid", "mpg": 48 },
    { "model": "RX450h", "fuel": "hybrid", "mpg": 43 },
    { "model": "NX300h", "fuel": "hybrid", "mpg": 45 },
    { "model": "UX250h", "fuel": "hybrid", "mpg": 47 },
    { "model": "RC F", "fuel": "petrol", "mpg": 24 },
    { "model": "IS F", "fuel": "petrol", "mpg": 23 },
    { "model": "LS500h", "fuel": "hybrid", "mpg": 36 },
    { "model": "RC300h", "fuel": "hybrid", "mpg": 44 },
    { "model": "NX350", "fuel": "petrol", "mpg": 35 },
    { "model": "ES300h", "fuel": "hybrid", "mpg": 49 }
  ],
  "Volvo": [
    { "model": "XC40", "fuel": "hybrid", "mpg": 46 },
    { "model": "XC60", "fuel": "hybrid", "mpg": 44 },
    { "model": "XC90", "fuel": "hybrid", "mpg": 42 },
    { "model": "S60", "fuel": "petrol", "mpg": 38 },
    { "model": "S90", "fuel": "hybrid", "mpg": 45 },
    { "model": "V40", "fuel": "diesel", "mpg": 50 },
    { "model": "V60", "fuel": "diesel", "mpg": 48 },
    { "model": "V90", "fuel": "diesel", "mpg": 46 },
    { "model": "C30", "fuel": "petrol", "mpg": 36 },
    { "model": "C70", "fuel": "petrol", "mpg": 34 },
    { "model": "S40", "fuel": "diesel", "mpg": 44 },
    { "model": "S70", "fuel": "diesel", "mpg": 42 },
    { "model": "S80", "fuel": "diesel", "mpg": 41 },
    { "model": "V50", "fuel": "diesel", "mpg": 45 },
    { "model": "V70", "fuel": "diesel", "mpg": 43 },
    { "model": "XC70", "fuel": "diesel", "mpg": 40 },
    { "model": "XC Classic", "fuel": "diesel", "mpg": 38 },
    { "model": "Polestar 1", "fuel": "hybrid", "mpg": 50 },
    { "model": "Polestar 2", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "S90 Recharge", "fuel": "hybrid", "mpg": 47 }
  ]
}
{
  "Tesla": [
    { "model": "Model S", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "Model 3", "fuel": "electric", "kwh_per_mile": 0.30 },
    { "model": "Model X", "fuel": "electric", "kwh_per_mile": 0.36 },
    { "model": "Model Y", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "Roadster", "fuel": "electric", "kwh_per_mile": 0.38 },
    { "model": "Cybertruck", "fuel": "electric", "kwh_per_mile": 0.40 },
    { "model": "Semi", "fuel": "electric", "kwh_per_mile": 0.45 },
    { "model": "Model S Plaid", "fuel": "electric", "kwh_per_mile": 0.35 },
    { "model": "Model X Plaid", "fuel": "electric", "kwh_per_mile": 0.37 },
    { "model": "Model 3 Long Range", "fuel": "electric", "kwh_per_mile": 0.31 },
    { "model": "Model 3 Standard", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "Model Y Long Range", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Model Y Performance", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "Roadster 2.0", "fuel": "electric", "kwh_per_mile": 0.36 },
    { "model": "Cyberquad", "fuel": "electric", "kwh_per_mile": 0.28 },
    { "model": "Model X 90D", "fuel": "electric", "kwh_per_mile": 0.36 },
    { "model": "Model S 85", "fuel": "electric", "kwh_per_mile": 0.33 },
    { "model": "Model 3 Performance", "fuel": "electric", "kwh_per_mile": 0.32 },
    { "model": "Model S Long Range", "fuel": "electric", "kwh_per_mile": 0.34 },
    { "model": "Model X Long Range", "fuel": "electric", "kwh_per_mile": 0.37 }
  ],
  "Subaru": [
    { "model": "Impreza", "fuel": "petrol", "mpg": 36 },
    { "model": "Forester", "fuel": "petrol", "mpg": 34 },
    { "model": "Outback", "fuel": "petrol", "mpg": 32 },
    { "model": "XV", "fuel": "petrol", "mpg": 35 },
    { "model": "BRZ", "fuel": "petrol", "mpg": 28 },
    { "model": "Levorg", "fuel": "petrol", "mpg": 33 },
    { "model": "Legacy", "fuel": "petrol", "mpg": 31 },
    { "model": "Trezia", "fuel": "petrol", "mpg": 37 },
    { "model": "Justy", "fuel": "petrol", "mpg": 40 },
    { "model": "Alcyone SVX", "fuel": "petrol", "mpg": 22 },
    { "model": "Forester e-BOXER", "fuel": "hybrid", "mpg": 40 },
    { "model": "XV e-BOXER", "fuel": "hybrid", "mpg": 42 },
    { "model": "Impreza WRX", "fuel": "petrol", "mpg": 28 },
    { "model": "WRX STI", "fuel": "petrol", "mpg": 26 },
    { "model": "Outback e-BOXER", "fuel": "hybrid", "mpg": 41 },
    { "model": "Levorg STI", "fuel": "petrol", "mpg": 29 },
    { "model": "Forester XT", "fuel": "petrol", "mpg": 27 },
    { "model": "BRZ tS", "fuel": "petrol", "mpg": 27 },
    { "model": "Legacy GT", "fuel": "petrol", "mpg": 25 },
    { "model": "Impreza Sport", "fuel": "petrol", "mpg": 33 }
  ],
  "Lotus": [
    { "model": "Evora", "fuel": "petrol", "mpg": 24 },
    { "model": "Exige", "fuel": "petrol", "mpg": 22 },
    { "model": "Elise", "fuel": "petrol", "mpg": 28 },
    { "model": "Emira", "fuel": "petrol", "mpg": 26 },
    { "model": "Europa S", "fuel": "petrol", "mpg": 25 },
    { "model": "Esprit", "fuel": "petrol", "mpg": 20 },
    { "model": "Elite", "fuel": "petrol", "mpg": 23 },
    { "model": "Elan", "fuel": "petrol", "mpg": 27 },
    { "model": "Exige Sport 410", "fuel": "petrol", "mpg": 22 },
    { "model": "Evija", "fuel": "electric", "kwh_per_mile": 0.36 },
    { "model": "Evora GT", "fuel": "petrol", "mpg": 23 },
    { "model": "Elise Cup 250", "fuel": "petrol", "mpg": 24 },
    { "model": "Emira GT", "fuel": "petrol", "mpg": 25 },
    { "model": "Exige Cup 430", "fuel": "petrol", "mpg": 21 },
    { "model": "Evora Sport 410", "fuel": "petrol", "mpg": 22 },
    { "model": "Elise Sprint 220", "fuel": "petrol", "mpg": 25 },
    { "model": "Emira First Edition", "fuel": "petrol", "mpg": 24 },
    { "model": "Evija Production", "fuel": "electric", "kwh_per_mile": 0.36 },
    { "model": "Elise SC", "fuel": "petrol", "mpg": 26 },
    { "model": "Exige S", "fuel": "petrol", "mpg": 22 }
  ],
  "Ferrari": [
    { "model": "488 GTB", "fuel": "petrol", "mpg": 18 },
    { "model": "488 Spider", "fuel": "petrol", "mpg": 17 },
    { "model": "Portofino", "fuel": "petrol", "mpg": 19 },
    { "model": "F8 Tributo", "fuel": "petrol", "mpg": 16 },
    { "model": "Roma", "fuel": "petrol", "mpg": 18 },
    { "model": "SF90 Stradale", "fuel": "hybrid", "mpg": 20 },
    { "model": "812 Superfast", "fuel": "petrol", "mpg": 15 },
    { "model": "California T", "fuel": "petrol", "mpg": 16 },
    { "model": "GTC4 Lusso", "fuel": "petrol", "mpg": 17 },
    { "model": "LaFerrari", "fuel": "hybrid", "mpg": 21 },
    { "model": "458 Italia", "fuel": "petrol", "mpg": 17 },
    { "model": "599 GTB Fiorano", "fuel": "petrol", "mpg": 16 },
    { "model": "Monza SP1", "fuel": "petrol", "mpg": 18 },
    { "model": "Monza SP2", "fuel": "petrol", "mpg": 18 },
    { "model": "812 GTS", "fuel": "petrol", "mpg": 15 },
    { "model": "F12berlinetta", "fuel": "petrol", "mpg": 14 },
    { "model": "SF90 Spider", "fuel": "hybrid", "mpg": 20 },
    { "model": "296 GTB", "fuel": "hybrid", "mpg": 22 },
    { "model": "Daytona SP3", "fuel": "petrol", "mpg": 16 },
    { "model": "Purosangue", "fuel": "petrol", "mpg": 17 }
  ],
  "Lamborghini": [
    { "model": "Huracan", "fuel": "petrol", "mpg": 15 },
    { "model": "Aventador", "fuel": "petrol", "mpg": 12 },
    { "model": "Urus", "fuel": "petrol", "mpg": 18 },
    { "model": "Sian", "fuel": "hybrid", "mpg": 14 },
    { "model": "Centenario", "fuel": "petrol", "mpg": 13 },
    { "model": "Veneno", "fuel": "petrol", "mpg": 11 },
    { "model": "Murcielago", "fuel": "petrol", "mpg": 12 },
    { "model": "Gallardo", "fuel": "petrol", "mpg": 14 },
    { "model": "Reventon", "fuel": "petrol", "mpg": 11 },
    { "model": "Diablo", "fuel": "petrol", "mpg": 10 },
    { "model": "Espada", "fuel": "petrol", "mpg": 9 },
    { "model": "Islero", "fuel": "petrol", "mpg": 10 },
    { "model": "Jarama", "fuel": "petrol", "mpg": 9 },
    { "model": "LM002", "fuel": "petrol", "mpg": 8 },
    { "model": "Countach", "fuel": "petrol", "mpg": 11 },
    { "model": "Sesto Elemento", "fuel": "petrol", "mpg": 12 },
    { "model": "Huracan EVO", "fuel": "petrol", "mpg": 14 },
    { "model": "Urus Performante", "fuel": "petrol", "mpg": 17 },
    { "model": "Aventador SVJ", "fuel": "petrol", "mpg": 12 },
    { "model": "Huracan STO", "fuel": "petrol", "mpg": 13 }
  ]
}
{
  "Dacia": [
    { "model": "Sandero", "fuel": "petrol", "mpg": 48 },
    { "model": "Sandero Stepway", "fuel": "petrol", "mpg": 46 },
    { "model": "Duster", "fuel": "diesel", "mpg": 42 },
    { "model": "Duster Eco-G", "fuel": "hybrid", "mpg": 45 },
    { "model": "Lodgy", "fuel": "diesel", "mpg": 38 },
    { "model": "Dokker", "fuel": "diesel", "mpg": 40 },
    { "model": "Logan", "fuel": "petrol", "mpg": 44 },
    { "model": "Logan MCV", "fuel": "diesel", "mpg": 42 },
    { "model": "Spring Electric", "fuel": "electric", "kwh_per_mile": 0.28 },
    { "model": "Dokker Van", "fuel": "diesel", "mpg": 39 },
    { "model": "Sandero RS", "fuel": "petrol", "mpg": 40 },
    { "model": "Duster Prestige", "fuel": "diesel", "mpg": 41 },
    { "model": "Sandero Comfort", "fuel": "petrol", "mpg": 47 },
    { "model": "Duster 4x4", "fuel": "diesel", "mpg": 37 },
    { "model": "Logan Stepway", "fuel": "petrol", "mpg": 45 },
    { "model": "Dokker Stepway", "fuel": "diesel", "mpg": 38 },
    { "model": "Duster Eco-G Prestige", "fuel": "hybrid", "mpg": 44 },
    { "model": "Spring Comfort", "fuel": "electric", "kwh_per_mile": 0.27 },
    { "model": "Sandero Essential", "fuel": "petrol", "mpg": 46 },
    { "model": "Lodgy Stepway", "fuel": "diesel", "mpg": 37 }
  ],
  "Formula1": [
    { "model": "Mercedes W12", "fuel": "petrol", "mpg": 3 },
    { "model": "Red Bull RB19", "fuel": "petrol", "mpg": 3 },
    { "model": "Ferrari SF21", "fuel": "petrol", "mpg": 2.8 },
    { "model": "McLaren MCL35M", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Alpine A521", "fuel": "petrol", "mpg": 2.8 },
    { "model": "AlphaTauri AT02", "fuel": "petrol", "mpg": 3 },
    { "model": "Aston Martin AMR21", "fuel": "petrol", "mpg": 2.7 },
    { "model": "Williams FW43B", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Mercedes W13", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Red Bull RB18", "fuel": "petrol", "mpg": 3 },
    { "model": "Ferrari SF90", "fuel": "petrol", "mpg": 2.8 },
    { "model": "McLaren MCL36", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Alpine A522", "fuel": "petrol", "mpg": 2.8 },
    { "model": "AlphaTauri AT03", "fuel": "petrol", "mpg": 3 },
    { "model": "Aston Martin AMR22", "fuel": "petrol", "mpg": 2.7 },
    { "model": "Williams FW44", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Mercedes W14", "fuel": "petrol", "mpg": 2.9 },
    { "model": "Red Bull RB20", "fuel": "petrol", "mpg": 3 },
    { "model": "Ferrari F1-75", "fuel": "petrol", "mpg": 2.8 },
    { "model": "McLaren MCL60", "fuel": "petrol", "mpg": 2.9 }
  ],
  "FighterJets": [
    { "model": "F-22 Raptor", "fuel": "jet fuel", "mpg": 0.5 },
    { "model": "F-35 Lightning II", "fuel": "jet fuel", "mpg": 0.45 },
    { "model": "Eurofighter Typhoon", "fuel": "jet fuel", "mpg": 0.4 },
    { "model": "Su-57 Felon", "fuel": "jet fuel", "mpg": 0.35 },
    { "model": "F-16 Fighting Falcon", "fuel": "jet fuel", "mpg": 0.42 },
    { "model": "F/A-18 Hornet", "fuel": "jet fuel", "mpg": 0.38 },
    { "model": "MiG-29 Fulcrum", "fuel": "jet fuel", "mpg": 0.37 },
    { "model": "Dassault Rafale", "fuel": "jet fuel", "mpg": 0.36 },
    { "model": "Saab JAS 39 Gripen", "fuel": "jet fuel", "mpg": 0.4 },
    { "model": "AV-8B Harrier", "fuel": "jet fuel", "mpg": 0.35 },
    { "model": "F-15E Strike Eagle", "fuel": "jet fuel", "mpg": 0.41 },
    { "model": "MiG-31 Foxhound", "fuel": "jet fuel", "mpg": 0.34 },
    { "model": "T-50 PAK FA", "fuel": "jet fuel", "mpg": 0.36 },
    { "model": "Chengdu J-20", "fuel": "jet fuel", "mpg": 0.33 },
    { "model": "Su-35", "fuel": "jet fuel", "mpg": 0.35 },
    { "model": "F-14 Tomcat", "fuel": "jet fuel", "mpg": 0.32 },
    { "model": "MiG-21", "fuel": "jet fuel", "mpg": 0.3 },
    { "model": "Mirage 2000", "fuel": "jet fuel", "mpg": 0.34 },
    { "model": "F-4 Phantom II", "fuel": "jet fuel", "mpg": 0.31 },
    { "model": "Su-34", "fuel": "jet fuel", "mpg": 0.33 }
  ]
}
